version: '3'

services:
  web2:
    image: bitnami/moodle:4
    ports:
      - 9202:8082
    environment:
      - APACHE_HTTP_PORT_NUMBER=8082
    env_file:
      - ./bitnami-moodle.env
    volumes:
      - vol_moodle:/bitnami/moodle
      - vol_moodledata:/bitnami/moodledata
    networks:
      - cluster2_net
    restart: always
  
  web3:
    image: bitnami/moodle:4
    ports:
      - 9203:8083
    environment:
      - APACHE_HTTP_PORT_NUMBER=8083
    env_file:
      - ./bitnami-moodle.env
    volumes:
      - vol_moodle:/bitnami/moodle
      - vol_moodledata:/bitnami/moodledata
    networks:
      - cluster2_net
    restart: always

volumes:
  vol_moodle:
    external: true
  vol_moodledata:
    external: true

networks:
  cluster2_net: