version: '3'

services:
  web1:
    image: bitnami/moodle:4
    ports:
      - 9201:8081
    environment:
      - APACHE_HTTP_PORT_NUMBER=8081
    env_file:
      - ./bitnami-moodle.env
    volumes:
      - vol_moodle:/bitnami/moodle
      - vol_moodledata:/bitnami/moodledata
    networks:
      - main_net
    depends_on:
      - db
    restart: always
  db:
    image: bitnami/postgresql:15
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=jaIQuO74xYhXCZCNRHXEghxYNJa8KKEW
      - POSTGRESQL_DATABASE=moodle
    networks:
      - main_net
    volumes:
      - vol_postgres:/bitnami/postgresql
    restart: always

networks:
  main_net:
volumes:
  vol_postgres:
    driver: local
  vol_moodle:
    external: true
  vol_moodledata:
    external: true
