version: '3'

services:
  web1:
    image: bitnami/moodle:4
    ports:
      - 9201:8081
    environment:
      - APACHE_HTTP_PORT_NUMBER=8081
    env_file:
      - ./bitnami-moodle.env
    volumes:
      - vol_moodle:/bitnami/moodle
      - vol_moodledata:/bitnami/moodledata
    networks:
      - main_net
    depends_on:
      - db
    restart: always
  db:
    image: bitnami/mariadb:10.6
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=jaIQuO74xYhXCZCNRHXEghxYNJa8KKEW
      - MARIADB_DATABASE=moodle
      - MARIADB_ROOT_PASSWORD=root
    networks:
      - main_net
    volumes:
      - vol_mariadb:/bitnami/mariadb
      - ./my.cnf:/opt/bitnami/mariadb/conf/my.cnf
    restart: always

networks:
  main_net:
volumes:
  vol_mariadb:
    driver: local
  vol_moodle:
    external: true
  vol_moodledata:
    external: true
